name: Build Desktop Apps

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json
            desktop/package-lock.json

      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

      - name: Build backend
        run: |
          cd backend
          npm run build

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Install desktop dependencies
        run: |
          cd desktop
          npm ci

      - name: Build desktop app (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          cd desktop
          npm run build:mac
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false

      - name: Build desktop app (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd desktop
          npm run build:linux
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false

      - name: Build desktop app (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd desktop
          npm run build:win:installer
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false

      - name: Upload artifacts (macOS)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: TaskFlow-macOS
          path: |
            desktop/dist/*.dmg
            desktop/dist/*.zip
          retention-days: 30

      - name: Upload artifacts (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: TaskFlow-Linux
          path: |
            desktop/dist/*.AppImage
            desktop/dist/*.deb
          retention-days: 30

      - name: Upload artifacts (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: TaskFlow-Windows
          path: |
            desktop/dist/*.exe
          retention-days: 30

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            desktop/dist/*.exe
            desktop/dist/*.dmg
            desktop/dist/*.zip
            desktop/dist/*.AppImage
            desktop/dist/*.deb
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
